export * from './Advantages/advantages'
export * from './ContactUs/contactUs'
export * from './Footer/footer'
export * from './Header/header'
export * from './Hero/hero'
export * from './Services/services'
export * from './WorkProcess/workProcess'
